### ISSUE TITLE
Call to undefined method _roundTotals()

### ISSUE THREAD

**Issue by srenon** [taxjar/taxjar-magento-extension#1]
Fatal error: Call to undefined method Taxjar_SalesTax_Model_Sales_Total_Quote_Tax::_roundTotals() in /app/code/community/Taxjar/SalesTax/Model/Sales/Total/Quote/Tax.php on line 130

Does this module support Magento EE 1.12.0.2?

**Comment by srenon** [comment]
`_roundTotals` method seem to be introduce in magento CE 1.8 app/code/core/Mage/Tax/Model/Sales/Total/Quote/Tax.php

**Comment by fastdivision** [comment]
Hi @srenon, this should be an easy fix. We can fall back to Magento's native `collect` method in this scenario and not call `_roundTotals` for Magento CE < 1.8. I attached a patch file and I'll get this pushed to the repo shortly. Thank you!

[magento-ce-1.7-patch.diff.zip](https://github.com/taxjar/taxjar-magento-extension/files/332371/magento-ce-1.7-patch.diff.zip)

**Comment by srenon** [comment]
@fastdivision ... Thanks
