### ISSUE TITLE
Wrong tax with Magentos Bundle SKUs

### ISSUE THREAD

**Issue by guidowerner** [taxjar/taxjar-magento-extension#3]
We recently started using TaxJar. We noticed that TaxJar has problems with handling multiple Magento bundle-products. So if debugged the extension and added a fix to the file app/code/community/Taxjar/SalesTax/Model/Smartcalcs.php 

The issue is that only the parent-bundle item has the correct quantity, the children-items are showing the quantity configured in Magento (so if 1 bundle consists of 1 screwdriver, 1 hammer, and 5 screws ) and you order 10 of them, TaxJar only calculates tax for 1 screwdriver, 1 hammer, and 5 screws instead of 10 screwdrivers, 10 hammers, and 50 screws.

I implemented a fix, to save the quantity for each parent and check multiplied the quantity for each child with the parent quantity.

I'm going to create a pull request against your git repo.
Guido

**Comment by fastdivision** [comment]
Fixed in [v2.3.3](https://github.com/taxjar/taxjar-magento-extension/tree/v2.3.3). Thanks @guidowerner!
