### ISSUE TITLE
Scope transaction sync store configuration to the current store

### ISSUE THREAD

**Issue by ryanreeves-taxjar** [taxjar/taxjar-magento-extension#32]
On branch "transaction sync", ensure the taxjar* configuration values are scoped to the local store.  

https://github.com/taxjar/taxjar-magento-extension/blob/transaction-sync/app/code/community/Taxjar/SalesTax/Model/Transaction/Comment.php#L32

**Comment by fastdivision** [comment]
Closing until we prioritize store-based transaction sync in Magento 1.

**Comment by JonLaliberte** [comment]
@ryanreeves-taxjar  Thanks for the answers!
