### ISSUE TITLE
Backup Rates error

### ISSUE THREAD

**Issue by JonLaliberte** [taxjar/taxjar-magento-extension#52]
As long as I can remember, Texas has shown an error:
<img width="321" alt="Screen Shot 2020-01-25 at 10 17 36 AM" src="https://user-images.githubusercontent.com/5403662/73123235-ea146380-3f5b-11ea-8ad8-436f52c030e1.png">

I've tried updating the address (it **does** have a zip code), but it never works.

**Comment by ryanreeves-taxjar** [comment]
Hi @JonLaliberte.  Please email our support team (support@taxjar.com) and we can help you investigate this issue.  Thanks!
