### ISSUE TITLE
Notice: Undefined offset: 1561820  in /<installpath>/.modman/taxjar-magento-extension/app/code/community/Taxjar/SalesTax/Model/Smartcalcs.php on line 228

### ISSUE THREAD

**Issue by drobinson** [taxjar/taxjar-magento-extension#6]
This notice is flooding the logs - seems there should be some `isset` checking on `$parentQuantities[$parentId]`.  Looks like this will always throw the notice in cases where the parent item is seen first in the items array.

**Comment by fastdivision** [comment]
@drobinson I'll get a fix up right away. Thanks for catching this!

**Comment by drobinson** [comment]
Thank you!
