### ISSUE TITLE
Incorrect Case Convention Used in Some Classnames 

### ISSUE THREAD

**Issue by ajbonner** [taxjar/taxjar-magento-extension#60]
Hey there

There are three observer classes using incorrect class name conventions (based on every other class in the module). Basically rather than Taxjar_SalesTax_xxx they are TaxJar_SalesTax_xxx (not the capital J in Jar).

The affected classes are 

[TaxJar_SalesTax_Model_Observer_AdminNotifications](https://github.com/taxjar/taxjar-magento-extension/blob/master/app/code/community/Taxjar/SalesTax/Model/Observer/AdminNotifications.php#L18)
[TaxJar_SalesTax_Model_Observer_AdminMenuItems](https://github.com/taxjar/taxjar-magento-extension/blob/master/app/code/community/Taxjar/SalesTax/Model/Observer/AdminMenuItems.php#L18)
[TaxJar_SalesTax_Model_Observer_ConfigReview](https://github.com/taxjar/taxjar-magento-extension/blob/master/app/code/community/Taxjar/SalesTax/Model/Observer/ConfigReview.php#L18)

These should be renamed To Taxjar_SalesTax_xxx.

Happy to submit a PR if you like.

Best
Aaron.

**Comment by fastdivision** [comment]
Thanks @ajbonner, we'll get these class names updated shortly 👍

**Comment by ryanreeves-taxjar** [comment]
PR updating these names:

https://github.com/taxjar/taxjar-magento-extension/pull/62
